// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package server

// Message defines model for message.
type Message struct {
	Message string `json:"message"`
}

// PersonID defines model for personID.
type PersonID = int
